language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      env:
        global:
          - PYCURL_CURL_CONFIG=/usr/local/opt/curl/bin/curl-config
          - LD_LIBRARY_PATH=/usr/local/opt/curl/lib:$LD_LIBRARY_PATH
          - PYCURL_SSL_LIBRARY=openssl

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install curl --with-openssl; brew install python; sudo easy_install pip; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install ruby ; fi
  - sudo gem install asciidoctor
  - pip install --user flake8
  - pip install --user nose
  - pip install --user pygments
  - pip install --user six
  - pip install --user wheel
  - git clone https://github.com/machacekondra/pdoc.git pdoc
  - pip install --user ./pdoc -U

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mvn package -DskipTests ; fi

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo pip install ./sdk -U ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis_wait 20 pdoc --overwrite --html --html-dir=target/generated-html/ sdk/lib/ovirtsdk4/ ; fi

deploy:
  - provider: script
    skip_cleanup: true
    script: automation/deploy-on-gh-pages.sh master
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = linux
  - provider: script
    skip_cleanup: true
    script: automation/deploy-on-gh-pages.sh tagged
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
