
name: ovirt-engine-sdk GitHub Actions

on: push

env:
  LD_LIBRARY_PATH: /usr/local/opt/curl/lib:$LD_LIBRARY_PATH
  PYCURL_SSL_LIBRARY: openssl

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Update packages
        run: sudo apt-get update

      - name: Install package dependencies
        run: sudo apt-get install mmv libssl-dev libcurl4-openssl-dev python-dev

      - name: Set git defaults
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Run maven build
        run: mvn package -Dskipflake=true -DskipTests -B

      - name: Set FOLDER variable according to pushed branch
        run: |
          if [[ ${GITHUB_REF} == 'refs/heads/master' ]];
          then
            echo "REMOTE_BRANCH=main" >> $GITHUB_ENV;
          else
            echo "REMOTE_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV;
          fi

      - name: Check out target repository
        uses: actions/checkout@v2
        with:
          repository: '${{ secrets.TARGET_REPO }}'
          ssh-key: '${{ secrets.DEPLOY_KEY }}'
          path: python-ovirt-engine-sdk4
          ref: '${{ env.REMOTE_BRANCH }}'

      - name: Copy SDK to repository
        run: |
          rm -rf sdk/target sdk/tests sdk/pom.xml
          cp -r sdk/* ./python-ovirt-engine-sdk4/

      - name: Push changes to python-ovirt-engine-sdk4
        run: |
          cd python-ovirt-engine-sdk4
          if git status --porcelain 2>/dev/null| grep -E "^??|^M"
          then
            git add .
            git commit -am "Sync with upstream"
            git push
          fi
          cd ..
